[build]
  base = "Frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"

[[redirects]]
  from = "/bot-api/*"
  to = "http://129.213.90.84:8001/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
