[build]
  base = "Frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from = "/bot-api/*"
  to = "http://129.213.90.84:8001/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
